#!/bin/bash
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

# Format and submit code according to lintstagedrc.js configuration
# 加⼊下⾯这⾏，否则npx会报命令找不到
PATH="/usr/local/bin:$PATH"
pnpm run lint:lint-staged
